###
GET {{baseUrl}}/buildInfo

> {%
    client.test("Request successfully", function () {
        client.assert(response.status == 200, "Response status is not 200")
    })
    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
    client.test("Check request body", function () {
        client.assert(response.body.hasOwnProperty("versions"), "should have a versions property")
        client.assert(response.body.versions.hasOwnProperty("yq"), "version of yq is available")
    })
%}